{{- if .Values.dags.git.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dags.git.secret }}
  labels:
    app: {{ include "airflow.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  id_rsa: {{ .Values.airflow.dags.sshKey | b64enc }}
  id_rsa.pub: {{ .Values.airflow.dags.sshKeyPub | b64enc }}
  known_hosts: {{ .Values.airflow.dags.knownHosts | b64enc }}
{{- end }}
